server:
    port: 9000

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: user-service
                  uri: ${USER_SERVICE_URL:http://localhost:8080}/users
                  predicates:
                      - Path=/users/**
                - id: tournament-service
                  uri: ${TOURNAMENT_SERVICE_URL:http://localhost:8081}/tournaments
                  predicates:
                      - Path=/users/**
            discovery:
                locator:
                    lower-case-service-id: true
                    enabled: true
                
eureka:
    client:
        enabled: false
         service-url:
             defaultZone: http://localhost:8761/eureka

