server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/users/**
        - id: tournament-service
          uri: ${TOURNAMENT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/tournaments/**
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/auth/**
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "${FRONTEND_URL:http://localhost:3000}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
