server:
    port: 9000

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    lower-case-service-id: true
                    enabled: true
                
eureka:
    client:
        enabled: false
        # service-url:
        #     defaultZone: http://localhost:8761/eureka

