server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/users/**
        - id: tournament-service
          uri: ${TOURNAMENT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/tournaments/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
